const SPONSOR_URL =
  'https://tetonflats.com/?utm_source=tetonpasscam&utm_medium=referral&utm_campaign=sponsor';

export default function Sponsor() {
  return (
    <section aria-label="Sponsor" className="mt-4">
      <div className="bg-sponsor-bg border-sponsor-border flex gap-3 rounded-card border p-4">
        {/* Generated by scripts/generate-sponsor-image.mjs from Drew's own
            kitchen-interior photo -- see that script's comment for why this
            is a .jpg (deliberately outside the PWA precache glob) rather
            than a .png like the app icons. */}
        <img
          src="/sponsor-tetonflats.jpg"
          alt="Teton Flats apartment interior"
          loading="lazy"
          className="w-28 shrink-0 self-stretch rounded-[10px] object-cover"
        />
        <div className="flex-1">
          <p className="text-sponsor-label text-[10.5px] font-bold uppercase tracking-wide">
            Created by{' '}
            <a href={SPONSOR_URL} className="underline">
              Teton Flats
            </a>
          </p>
          <p className="mt-1 text-sm">
            {' '}
            — 1 &amp; 2 bed apartments in Victor, 35 minutes from Jackson, save thousands of
            dollars.
          </p>
        </div>
      </div>
    </section>
  );
}
